### ISSUE TITLE
Web3.js and Ethers.js Interoperability

### ISSUE THREAD

**Issue by holgerd77** [ethereum/js-team-organization#1]
This issue is for identifying and discussing main pain points on interoperability between the [Web3.js](https://github.com/ethereum/web3.js) and [Ethers.js](https://github.com/ethers-io/ethers.js) libraries.

Suggested topics for discussion:

- Common API standards
- Migration pitfalls
- Irritating behavioral deviations (expected: same behavior, reality: different behavior)
- Others

**Comment by holgerd77** [comment]
@ricmoo Whew, that was quick! 😋

**Comment by nivida** [comment]
@ricmoo We do have two points where we have to be compatible with each other: 

1. Ethers AbiCoder
2. Web3.js Providers

Do you agree? 

Any further interoperability between Ethers and Web3 depends on EthereumJS and the related packages. (ethereumjs-tx, ethereumjs-common, and ethereumjs-utils)

**Comment by ricmoo** [comment]
I agree on the coder.

I don't really agree on Provider. I feel Web3 Provider is meant to closely match the functionality of the JSON-RPC, while the ethers.js Provider is meant as a higher-level abstraction.

For example, a Web3 Provider aims to expose Account-level and Blockchain-level functionality, while ethers requires a Provider and a Signer. I think it is important to be able to move between the two though, which is what the Web3Provider aims to do, wrapping a Web3 provider (or other EIP-1193 provider) to expose a ethers.js Provider. Also, I (think) I have a grant allocated to bounty fixing up the Web3Bridge, which goes the other direction; wrapping an ethers.js provider and signer to expose a Web3-compatible provider.

This may make more sense in the future, but that would require some more thinking; for example in *ethers-app*, I've avoided the term `Provider` entirely, as I think it is heavily overloaded in the space. It instead exposes a `Blockchain` object, which I think captures the fact that it only contains public data while the `Account` object captures that it allows access to private data.

**Comment by holgerd77** [comment]
Just a meta-note: you don't have to come to short-term agreements here, I think it's already very much worth the exchange.

If there isn't agreement on stuff this can also very much lead to lower level changes, like adoptions or mentions in the docs e.g. ("Hey guys, watch out! This is different!").

😄

**Comment by ricmoo** [comment]
Yes, that is a good point. Im going to add a `_note:` to Flatworm, I'll use Web3.js differences as a test of that feature and add those notes to the docs this week. :)

**Comment by nivida** [comment]
> I don't really agree on Provider. I feel Web3 Provider is meant to closely match the functionality of the JSON-RPC, while the ethers.js Provider is meant as a higher-level abstraction.

> For example, a Web3 Provider aims to expose Account-level and Blockchain-level functionality, while ethers requires a Provider and a Signer. I think it is important to be able to move between the two though, which is what the Web3Provider aims to do, wrapping a Web3 provider (or other EIP-1193 provider) to expose a ethers.js Provider. Also, I (think) I have a grant allocated to bounty fixing up the Web3Bridge, which goes the other direction; wrapping an ethers.js provider and signer to expose a Web3-compatible provider.

The providers were never thought to be used for signing. As I know was it mainly the community who started to use this "hack" as a feature to alter the behaviour of Web3.js. 
What I was meaning was [this](https://docs.ethers.io/ethers.js/html/cookbook-providers.html?#metamask) and I totally agree that we should separate the transaction signing from providing of the JSON-RPC abstraction. :)

> This may make more sense in the future, but that would require some more thinking; for example in ethers-app, I've avoided the term Provider entirely, as I think it is heavily overloaded in the space. It instead exposes a Blockchain object, which I think captures the fact that it only contains public data while the Account object captures that it allows access to private data.

Awesome! 💪

**Comment by holgerd77** [comment]
Outdated, will close.
