### ISSUE TITLE
EF JS Team > Knowledge Transfer

### ISSUE THREAD

**Issue by nivida** [ethereum/js-team-organization#10]
Hey All! 

The Minerva security vulnerability has brought up some homework many of us have to do. On the other hand, do we already have members in the EF JS Team who do have a deeper knowledge base on this topic (lattice attacks, etc.).  

Because we are a big team now with a lot of different expertise in different computer science-related topics. Do we have to ask us how we share such knowledge in an efficient and sustainable way over the whole EF JS Team?

Ideas: 

- a 10min introduction presentation to a specific topic with followed up reading material on each team call.
- Writing blog posts for us and the community about specific topics. 
- Creating a cheat-sheet with various references to read worthy resources related to computer science or also project management.
- Inviting of specific Ethereum Foundation members. For example, Axic to get a deeper insight into eWASM and EE's.

How does the rest of the team think about such a knowledge transfer?

**Comment by evertonfraga** [comment]
I think this idea is super good, especially about #4. Such conversations can be of an immense value and cut down some valuable study time.

**Comment by holgerd77** [comment]
We might also want to think about if it might might make sense to make extra calls on certain topics.

**Comment by nivida** [comment]
@evertonfraga Yes, the 4th point is definitely the most interesting point for all of us. 

@holgerd77 Yep, I think a short 10min presentation from someone of the EF JS Team can be done during the team call but if we invite an expert from the EF to a specific topic or if it is a bigger topic is it definitely worth to think about a separate call where we actually have the time for a longer question/answer session.

The question we have now regarding knowledge transfer presentations is how do we organize it:

- Do we organize such knowledge transfer on request and if enough EF JS team members are interested in? or would we organize it the opposite way which means on offer from an EF JS team member or someone else from the EF? or both?
- Where and how do we list such offers or requests?

> Creating a cheat-sheet with various references to read worthy resources related to computer science or also project management.

This is probably not required because https://ethereum.org/ should exactly be this resources hub and we should extend it if something is missing. 🤔 

> Writing blog posts for us and the community about specific topics.

This could be done after an internal knowledge transfer happened and in the best case should someone write it which didn't present the topic. I think it would increase the sustainability of those knowledge transfer.

**Comment by holgerd77** [comment]
No further follow-up on this, will close, idea remains generally interesting though.
