### ISSUE TITLE
EIP-1559 (Fee market change) Tracking & Discussion Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereum/js-team-organization#17]
And another strategy issue: [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559) with a proposal for a changed gas fee market model is gaining more and more traction.

Just dropping this here. We might want to see if we want to engage more here. Eventually it is also time to think about starting on implementations (someone might want to write down here on the potential changes needed respectively libraries touched), an estimated (super-unoffical) timeline here is a by-year-end mainnet adoption.

Some references:

- [EIP-1559 Implementers Call](https://github.com/ethereum/pm/issues/174) (taking Call 2 as a random entry point on `ethereum/pm`)
- [EIP-1559 Channel on Eth R&D Discord](https://github.com/ethereum/pm/issues/174)
- [Twitter Tim Beiko](https://twitter.com/TimBeiko) with excellent call summaries, e.g. [this tweet](https://twitter.com/TimBeiko/status/1265989911225798662) on Call 2 and other EIP-1559 related information

**Comment by jochem-brouwer** [comment]
General comment here: I think the focus for now should be to get client/vm ready to support each other, so we can implement a sync on the client (probably full sync first as this is the "easiest" here IMO). As a side project we can slowly start to implement this EIP (but one with rather high priority). It would be great to get the client ready so we can participate in testnets and thus also participate in a testnet for EIP 1559 which I assume is very likely to happen.

**Comment by holgerd77** [comment]
Not used and outdated, will close.
