### ISSUE TITLE
EF JS team shared resources > Org Docs

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/js-team-organization#4]
EthereumJS has a similar [organization repo](https://github.com/ethereumjs/organization) that contains documentation and label management. Should the new JS team have any shared documentation? @holgerd77 mentioned a possible web presence for the new team; maybe this is a good place to discuss what belongs there. A natural starting point is to introduce each project with relevant links, but from there it could get more interesting with shared practices, onboarding, etc.

**Comment by holgerd77** [comment]
Hi Marc, also thought about this a couple of times, I think a shared documentation for the new team would make very much sense. Could you eventually take this over as some mid-size project during the next weeks if we generally agree that this is useful? That would be great!

I've put a lot of effort in this [EthereumJS documentation](https://ethereumjs.readthedocs.io/) would love to see if we can reuse some/larger parts of this. I think it is too much of a one-time burden to just make one large PR with all the necessary changes and just take the documentation over. This would likely cause too much friction and discussion on too many places.

So if we want to build upon that I would suggest that me start fresh on the this repo, but likely reuse all the structural parts + content which makes sense (or we adopt the content). We could make this here as separate PRs for the different parts, then everyone also has a chance to jump into the discussion and we can agree together what we take over in what form. Along we can eventually directly downgrade the EthereumJS documentation, e.g. do a PR there to remove the content if we take something completely over.

Will just go through the chapters with some notes:

TODO

**Comment by holgerd77** [comment]
Have updated the post above with some notes on the existing EthereumJS docs, have to be read online for the full picture. 😄

**Comment by marcgarreau** [comment]
Happy to play a role in writing/editing copy and having some ownership of this. The more difficult part may be reaching agreement on practices employed by all projects - or at least meaningfully specific ones. I suspect each has its own slightly different version best practices and so on. Identifying common ground could a good topic for the next team meeting, but as a starting point, we can also run through each project README and see if we can identify some commonalities and divergences. I'll take a pass at that next week.

**Comment by holgerd77** [comment]
@marcgarreau Ok, great! I think it is already a good start if we have the central structure on the docs ready. We can then do the conversation on various practices and if or if not to unify to a single standard on the separate PRs over time.

But we can very well also start some base discussion there - shouldn't put the expectation on agreements too high though, think it's already worth to get started here a bit, this generally needs some time.

Have opened a new topic for the next call (see Gitter).

**Comment by marcgarreau** [comment]
@holgerd77 research doc added to the next meeting agenda.

**Comment by marcgarreau** [comment]
Have been evaluating a few static site doc generators: read the docs, docsify, docz. [docz](https://www.docz.site) is my clear favorite at this point:
- powered by Gatsby
- produces the familiar Read The Docs-like layout, with search and light/dark modes out of the box.
- uses MDX -- markdown with JSX support -- so you can add arbitrary react components. This makes it ~infinitely customizable (above and beyond themes).
- build process is a breeze and outputs static files to be deployed however we choose.
- bonus features, e.g. in development, a graphql server with all the site data is spun up for free.

Will finish the repo skeleton and push up to a branch here for testing.

**Comment by ricmoo** [comment]
As a quick note, I created [flatworm](https://github.com/ricmoo/flatworm) for the new ethers documentation, which dumps out [html docs](https://docs-beta.ethers.io) and [markdown directly within GitHub](https://github.com/ethers-io/ethers.js/tree/ethers-v5-beta/docs#what-is-ethers).

I'm certainly not recommending it for general consumption as I'm still introducing large non-backwards compatible changes. Just pointing it out.

Some unique-ish (I think?) features:

- All code samples are executed during docs generation; if these is an error in the code samples, it fails, and the docs examples never disagree with the output
- Generates HTML and GitHub markdown (see above links)
- JavaScript-specific to create nicely formatted API headings

Things coming soon:

- JavaScript sandbox so people can experiment with code samples throughout the docs
- Linking each function to its TypeScript source
- More generic output format plugins (i.e. I want to easily export a PDF via LaTeX)
- Static search generation
- Expose internal links on mouse-over

**Comment by marcgarreau** [comment]
Amazing that you find time for it, first of all. The freshly executed code samples, sandbox, TS source, etc. sound especially valuable for a lib like ethers.js. That does spur the question of what else we might want to host in these cross-team docs. My instinct is that it will primarily be copy, links, other static content, but that could be lack of imagination. 

If its just static content, I think docz is the right fit for this use case. If we want to dream up good uses for code playgrounds and more, I'd be glad to reevaluate flatworm when the features are ready. The site content will just be markdown files (well, mdx, but close enough), so it shouldn't be much trouble to port them over to another site generator that is markdown-friendly.

**Comment by holgerd77** [comment]
Could remember my main reason why I decided against the [markdown ReadTheDocs version](https://markdown-guide.readthedocs.io/en/latest/): the markdown syntax didn't allow for relatively stable URLs. With RST you have got the chapter referencing separated from the readable titles, e.g. you start a section with:

```RST
.. _roadmap_active:

Active Projects
===============
```

The anchor and the readable title are separated, and one is referencing the specific section by ":ref:`roadmap_active`" so using the well-defined anchor and not the title. In markdown the URL is directly created from the section title, so if "Active Projects" is changed by someone to "Current Active Projects" in the markdown version the old URL is lost.

I find the point of having stable documentation URLs pretty important for having through-time reliable linking and for EthereumJS that was the main point to decide against markdown.

That said I wouldn't make this a blocker or put some strong opinion against markdown here. As I said in the call from a syntactical point I would prefer markdown over RST as well. And *Docz* seems to be a well established tool and a JS-based tool is likely a more natural fit for our team.

Nevertheless wanted to make this somewhat broader statement from above for awareness and discussion. Maybe there is some way to also achieve this with the new tool (URL stability) or it is eventually already integrated (?). Anyhow: if not we should at least have this on the plate and choose our doc titles carefully to minimize the loss here.

**Comment by nivida** [comment]
@holgerd77 
Such anchors are possible in markdown with the HTML anchor tag: 
```
### <a name="first-title"></a> First Title 

[link](#first-title)
```

**Comment by ricmoo** [comment]
I certainly agree stable doc URLs are very important.

One other note on reStructured, there are two syntaxes for linking, and one requires “backward declaration” (or whatever the opposite of forward declaration would be) while the other does not allow in-page linking. Or something like that. I recall having a difficult time using consistent link syntax across the documentation.

**Comment by marcgarreau** [comment]
Hey guys :wave: Once upon a time, I wrote [this draft](https://medium.com/@wolovim/an-introduction-to-ethereumjs-1d1d1ea24f6c) to help onboard potential contributors, but it got lost in the shuffle. Some pieces have become stale, but I would imagine much of it is still relevant. Please feel free to use any (or none) of it. Note that Medium requires you to be signed in to read drafts now.

**Comment by holgerd77** [comment]
Hi @marcgarreau, hope everything is fine, thanks for dropping here! Yes, you're right, this got a bit forgotten. This was a really nice article and we should really make sure that we make use of it not too far in the future, so that it won't age too much.

**Comment by holgerd77** [comment]
A unified documentation setup is not planned respectively useful any more within the current team constallation.

Will close.
